### ISSUE TITLE
Missing border when tabs are inconsistent number of lines

### ISSUE THREAD

**Issue by radumas** [Grasia/grasia-dash-components#1]
@Akronix very kindly shared [this demo](https://test-grasia-dash-components.herokuapp.com/) when I asked about Tab display on mobile in this thread on Dash Core Components https://github.com/plotly/dash-core-components/pull/74

I wanted to highlight a minor issue this implementation has, that the border appears to be missing when the number of lines in each tab is inconsistent.

![image](https://user-images.githubusercontent.com/10623872/33566440-04b70282-d8ee-11e7-9999-40e278a05895.png)

**Comment by Akronix** [comment]
Thank you @radumas for reporting.
The fix is ready and will be released tomorrow.

**Comment by Akronix** [comment]
I have to delay it for tomorrow, but rest assured that I'll be available soon.

**Comment by Akronix** [comment]
Fixed in 0.0.4, please @radumas upgrade and let me know if you find any other issue.
