### ISSUE TITLE
GDC not on Unpkg?

### ISSUE THREAD

**Issue by guillochon** [Grasia/grasia-dash-components#3]
It appears that GDC is not available on unpkg? The following returns a 404:

https://unpkg.com/grasia-dash-components@0.3.4/grasia_dash_components/bundle.js

**Comment by Akronix** [comment]
Thank you for pointing this out @guillochon.
GDC is in unpkg but it seems that something is broken there: https://unpkg.com/grasia-dash-components@0.3.4/
I am not sure about what is the way to go with unpkg for Dash components. Maybe @chriddyp Can give me a any insight of how good building configuration for unpkg looks like?

**Comment by Akronix** [comment]
https://unpkg.com/grasia-dash-components@0.3.4/grasia_dash_components/bundle.js works now :man_shrugging: 
No idea what fixed it but let's close this for now.
