### ISSUE TITLE
dash.exceptions.DuplicateIdError

### ISSUE THREAD

**Issue by mbkupfer** [Grasia/grasia-dash-components#7]
Hi, I tried testing out the usage.py and got the below exception. It got stuck on the Flask debugger screen.

```
dash.exceptions.DuplicateIdError

dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `test-card`
```

**Comment by Akronix** [comment]
I can't reproduce the issue, did you change anything from the usage.py file?

**Comment by Akronix** [comment]
@mbkupfer feel free to reopen it if you face the problem again.
